# 20장. 뒷정리하기

- ~~테스트 메서드 호출하기~~
- ~~먼저 setUp 호출하기~~
- <B>나중에 tearDown 호출하기</B>
- 테스트 메서드가 실패하더라도 tearDown 호출하기
- 여러 개의 테스트 실행하기
- 수집된 결과를 출력하기
- <B>WasRun에 로그 문자열 남기기</B>



가끔은 setUp()에서 외부 자원을 할당하는 경우가 있다.

외부 자원을 할당 받은 테스트들은 작업을 마치기 전에 tearDown() 메서드 같은 곳에서 자원을 다시 반환할 필요가 있다.

단순하게 플래그를 도입하는 방법이 있지만 이는 귀찮게 만든다.

플래그를 사용하면 setUp()은 테스트 메서드 전, tearDown()은 테스트 메서드 실행 후 호출되어야 한다는 점을 놓친다.

그래서 난 호출된 메서드의 로그를 간단히 남기는 식으로 테스트 전략을 바꾸겠다.

```python
class WasRun(TestCase):
    def __init__(self, name):
        TestCase.__init__(self, name)
    
    def testMethod(self):
        self.wasRun = 1
	
    def setUp(self):
        self.wasRun = None
        self.wasSetUp = 1
        self.log = "setUp" # 추가
```



이제 testSetUp()이 플래그 대신에 로그를 검사하도록 변경할 수 있다.

```python
class TestCaseTest(TestCase):
    def setUp(self):
        self.test = WasRun("testMethod")
        
    def testRunning(self):
        self.test.run()
        assert(self.test.wasRun)
    
    def testSetUp(self):
        self.test.run()
        assert("setUp" == self.test.log) # 수정
```



다음엔 wasSetup 플래그를 지울 수 있다. 그리고 테스트 메서드의 실행을 기록할 수도 있다.

```python
class WasRun(TestCase):
    def __init__(self, name):
        TestCase.__init__(self, name)
    
    def testMethod(self):
        self.wasRun = 1
        self.log = self.log + "testMethod"
	
    def setUp(self):
        self.wasRun = None
        self.wasSetUp = 1
        self.log = "setUp"
```

이 작업은 testSetUp을 실패하게 만든다. 왜냐하면 실제 로그는 'setUp testMethod'이기 때문이다. 예상되는 값 부분을 바꾸자.

```python
class TestCaseTest(TestCase):
    def setUp(self):
        self.test = WasRun("testMethod")
        
    def testRunning(self):
        self.test.run()
        assert(self.test.wasRun)
    
    def testSetUp(self):
        self.test.run()
        assert("setUp testMethod" == self.test.log) # 수정
```



이제 이 테스트는 두 개의 테스트가 할 일을 모두 수행한다. 따라서 test-Running을 지우고 testSetUp의 이름을 바꿔주자.

```python
class TestCaseTest(TestCase):
    def setUp(self):
        self.test = WasRun("testMethod")
       
    # 수정
    def testTemplateMethod(self):
        self.test.run()
        assert("setUp testMethod" == self.test.log)
```



불행히도 WasRun의 인스턴스를 한 곳에서만 사용하므로 setUp부분을 되돌려야 한다.

```python
class TestCaseTest(TestCase):
    def setUp(self):
        self.test = WasRun("testMethod")
       
    def testTemplateMethod(self):
        self.test = WasRun("testMethod") # 추가
        self.test.run()
        assert("setUp testMethod" == self.test.log)
```



이제 tearDown()을 ~~구현할~~ 테스트할 준비가 됐다.

```python
class TestCaseTest(TestCase):
    def setUp(self):
        self.test = WasRun("testMethod")
       
    def testTemplateMethod(self):
        test = WasRun("testMethod") 
        test.run()
        assert("setUp testMethod tearDown " == self.test.log) # 수정
```

실패한다.



```python
class TestCase:
    def setUp(self):
        pass
    
    def __init__(self, name):
        self.name = name
        
    def run(self):
        self.setUp()
        method = getattr(self, self.name)
        method()
        self.tearDown() # 추가
```

```python
class WasRun(TestCase):
    def __init__(self, name):
        TestCase.__init__(self, name)
    
    def testMethod(self):
        self.log = self.log + "testMethod "
	
    def setUp(self):
        self.log = "setUp "
       
    # 추가
    def tearDown(self):
        self.log = self.log + "tearDown "
```

이러면 TestCaseTest에서 에러가 난다. (tearDown()을 구현하지 않았기 때문)



```python
class TestCase:
    def setUp(self):
        pass
    
    def __init__(self, name):
        self.name = name
        
    def run(self):
        self.setUp()
        method = getattr(self, self.name)
        method()
        self.tearDown()
        
    # 추가
    def tearDown(self):
        pass
```



이번 장에서 한 걸 검토해 보자. 우리는

- 플래그에서 로그로 테스트 전략을 구조 조정했다.
- 새로운 로그 기능을 이용하여 tearDown()을 테스트하고 구현했다.
- 문제를 발견했는데 뒤로 되돌아가는 대신 과감히 수정했다 (이게 잘한 일일까?).