# 21장. 셈하기

>~~테스트 메서드 호출하기~~
>
>~~먼저 setUp 호출하기~~
>
>~~나중에 tearDown 호출하기~~
>
>테스트 메서드가 실패하더라도 tearDown 호출하기
>
>테스트 여러 개 실행하기
>
>**수집한 결과를 출력하기**
>
>~~WasRun에 로그 문자열 남기기~~



난 테스트 메서드에서 예외가 발생하건 말건 tearDown()이 호출되도록 보장해 주는 기능을 구현하려고 했다.

하지만 테스트가 작동하도록 하려면 예외를 잡아야 한다.

일반적으로 테스트를 구현하는 순서는 중요하다.



우린 여러 테스트를 실행하고 그 결과를 다음과 같이 보길 원한다.

`"5개 테스트가 실행됨, 2개 실패, TestCaseTest.testFooBar-ZeroDivide Exception, MoneyTest.testNegation-AssertionError"`

- 그러면 테스트들이 더는 호호출되지 않든지, 결과 보고가 멈추든지 간에 우리에게는 그 에러를 잡을 기회가 있다.
- 우리는 TestCase.run()이 테스트 하나의 실행 결과를 기록하는 **TestResult 객체를 반환하게 만들것이다.**



---

#### 📌 TestCaseTest

```python
def testResult(self):
	test = WasRun("testMethod")
  result = test.run()
  assert("1 run, 0 failed" == result.summary())
```

#### 📌 TestResult

```python
class TestResult:
  def summary(self):
    return "1 run, 0 failed"
```

그리고 TestCase.run()이 TestResult를 반환한다.

#### 📌 TestCase

```python
def run(self):
  self.setUp()
  method = getattr(self, self.name)
  method()
  self.tearDown()
  return TestResult()
```

---

summary의 구현을 조금씩 실체화 할 수 있다.

먼저 테스트의 수를 상수로 만들 수 있다.

#### 📌 TestResult

```python
class TestResult:
  def __init__(self):
    self.runCount = 1
  def summary(self):
    return "%d run, 0 failed" % self.runCount
```



---

하지만  runCount는 상수일 수 없다.

0으로 초기화하고 테스트가 실행될 때 마다 1씩 증가시키게 만든다.

#### 📌 TestResult

```python
class TestResult:
  def __init__(self):
    self.runCount = 0
  def testStarted(self):
    self.runCount = self.runCount + 1
  def summary(self):
    return "%d run, 0 failed" % self.runCount
```



---

이제 실제로 호출하게 만들어야 한다.

#### 📌 TestCase

```python
def run(self):
  result = TestResult()
  result.testStarted()
  self.setUp()
  method = getattr(self, self.name)
  method()
  self.tearDown()
  return result
```

---

아직 실패하는 테스트 수를 나타내는 상수도 runCount 처럼 변수로 만들 수 있겠지만,

이 작업을 하게 끔 만들어주는 테스트가 아직 없으므로 작성한다.

#### 📌 TestCaseTest

```python
def testFailedResult(self):
  test = WasRun("testBrokenMethod")
  result = test.run()
  assert("1 run, 1 failed" == result.summary())
```

#### 📌 WasRun

```python
def testBrokenMethod(self):
	raise Exception
```



---

<br>

WasRun.testBrokenMethod에서 던진 예외를 처리하지 않았다. 

잠시 할일 목록에 남겨두자~



#### 이번 장에서 우리는

- 가짜 구현을 한 뒤에 단계적으로 상수를 변수로 바꾸어 실제 구현으로 만들었다.
- 또 다른 테스트를 작성헀다.
- 테스트가 실패했을 때 좀더 작은 스케일로 또 다른 테스트를 만들어서 실패한 테스트가 성공하게 만드는 것을 보조할 수 있었다.
